version: '3'

volumes:
  static:
  payment_data:

services:
  postgres:
    container_name: payment_postgres
    image: postgres:14.1-alpine
    env_file: envs/webstore.env
    volumes:
      - payment_data/:/var/lib/postgresql/data/

  backend:
    container_name: payment_django
    env_file: envs/webstore.env
    build:
      context: ..
      dockerfile: docker/dockerfiles/PaymentDockerfile
    volumes:
      - static:/usr/src/app/static
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:1.21.6-alpine
    container_name: payment_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static:/data/static
    depends_on:
      - backend
    ports:
      - "80:80"